"""Golden characterization tests for the pre-refactor mixture estimators."""

import numpy as np
import pandas as pd
import pytest

from hmda_seconds import (
    gradient_boosting,
    logistic_features,
    mixture,
    random_forest_mixture,
)
from hmda_seconds.density_ratio import (
    FittedDensityRatioModel,
    evaluation,
    folds,
)


def _synthetic_frame(n: int, year: int, seed: int) -> pd.DataFrame:
    """Return a deterministic labeled frame shared by all model families."""
    rng = np.random.default_rng(seed)
    log_lti = rng.normal(size=n)
    log_value_to_loan = rng.normal(size=n)
    purchaser_type = rng.integers(0, 10, size=n)
    loan_type = rng.integers(1, 5, size=n)
    latent_index = (
        -1.7
        + 0.85 * log_lti
        - 0.35 * log_value_to_loan
        + 0.12 * (purchaser_type == 1)
        + 0.18 * (loan_type == 2)
    )
    second = rng.random(n) < 1.0 / (1.0 + np.exp(-latent_index))
    return pd.DataFrame(
        {
            "year": year,
            "lien_status": np.where(second, 2, 1),
            "log_lti": log_lti,
            "log_county_value_to_loan": log_value_to_loan,
            "purchaser_type": purchaser_type,
            "loan_type": loan_type,
        }
    )


def _signature(model, target: pd.DataFrame, fold) -> dict[str, object]:
    evaluated = evaluation.evaluate_target(
        model,
        target,
        fold,
        label_var="lien_status",
        second_lien_class=2,
    )
    result = evaluated.result
    return {
        "log_ratio_head": evaluated.log_ratio[:5],
        "mixture_share": result.mixture_share,
        "probability_head": evaluated.probability[:5],
        "brier_score": result.brier_score,
        "mean_probability": result.mean_probability,
        "hard_share_050": result.hard_share_050,
    }


def test_pre_refactor_density_ratio_family_outputs_are_frozen():
    """Detect numerical drift while the common evaluator is introduced."""
    training = pd.concat(
        [
            _synthetic_frame(800, 2005, 17),
            _synthetic_frame(800, 2006, 29),
        ],
        ignore_index=True,
    )
    target = _synthetic_frame(600, 2004, 41)

    logistic = mixture.fit_known_source_prior_model(
        training,
        logistic_features.FeatureSpecification("linear", "none"),
        regularization_c=0.1,
    )
    boosting, _ = gradient_boosting.fit_boosting_ratio_model(
        training,
        gradient_boosting.BoostingParameters(
            max_leaf_nodes=7,
            learning_rate=0.1,
            max_iter=20,
            l2_regularization=1.0,
            min_samples_leaf=20,
        ),
    )
    forest, _ = random_forest_mixture.fit_forest_ratio_model(training)

    fitted = {
        "logistic": logistic,
        "gradient_boosting": boosting,
        "random_forest": forest,
    }
    assert all(isinstance(model, FittedDensityRatioModel) for model in fitted.values())
    fold = folds.temporal_fold((2005, 2006), (2004,), direction="reverse")
    actual = {
        family: _signature(model, target, fold) for family, model in fitted.items()
    }

    # Values generated by the pre-refactor implementations on the deterministic
    # sample above. Array and scalar tolerances permit harmless floating-point
    # differences while remaining tight enough to detect evaluation drift.
    expected = {
        "logistic": {
            "log_ratio_head": np.array(
                [-1.29157278, 0.01227075, -1.29477809, -0.07736976, -1.59695703]
            ),
            "mixture_share": 0.22120957952512443,
            "probability_head": np.array(
                [0.07241277, 0.22333076, 0.07219777, 0.20816844, 0.05439316]
            ),
            "brier_score": 0.13520568867330718,
            "mean_probability": 0.22120958002594743,
            "hard_share_050": 0.07333333333333333,
        },
        "gradient_boosting": {
            "log_ratio_head": np.array(
                [-1.62831439, 0.51038859, -0.72069953, -0.86971566, -1.59272588]
            ),
            "mixture_share": 0.09705377381016526,
            "probability_head": np.array(
                [0.02065934, 0.15186998, 0.04968467, 0.04310257, 0.02139180]
            ),
            "brier_score": 0.14501821968500161,
            "mean_probability": 0.09705377351317102,
            "hard_share_050": 0.0,
        },
        "random_forest": {
            "log_ratio_head": np.array(
                [-0.48396157, 0.80701898, -1.25278713, -1.26896399, -2.30235978]
            ),
            "mixture_share": 4.737685956874163e-09,
            "probability_head": np.array(
                [
                    2.92001062e-09,
                    1.06181818e-08,
                    1.35359186e-09,
                    1.33187116e-09,
                    4.73875358e-10,
                ]
            ),
            "brier_score": 0.18333333059626566,
            "mean_probability": 4.405312670887999e-09,
            "hard_share_050": 0.0,
        },
    }
    for family, expected_signature in expected.items():
        for name, expected_value in expected_signature.items():
            assert actual[family][name] == pytest.approx(
                expected_value, rel=1e-6, abs=1e-10
            )
